#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Motor,  port2,           dm_n,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           dm_s,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           dm_w,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           dm_e,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           cpm_l,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           cpm_r,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rm_l,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rm_r,            tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*

Motor mappings:

1. RESERVED
2. dm_n Drive Motor North
3. dm_s Drive Motor South
4. dm_w Drive Motor West
5. dm_e Drive Motor East
-----------------------------
6. cpm_l Catapault Motor Left
7. cpm_r Catapault Motor Right
-----------------------------
8. rm_l Release Motor Left
9. rm_r Release Motor Right

*/
int speedLimit = 127;
int tInc = 0;
int tickRate = 30;

/*
Declare joystick vars.
Follows the U,D,L,R notation.
*/
int j1[4] = {0, 0, 0, 0};
int j2[4] = {0, 0, 0, 0};
int j3[4] = {0, 0, 0, 0};
int j4[4] = {0, 0, 0, 0};
int j5[2] = {0, 0};
int j6[2] = {0, 0};

int mathNegative(int input) {
	if (input > 0) {
		return input - (input * 2);
	} else if (input == 0) {
		return 0;
	} else if (input < 0) {
		return input;
	}
	return 1;
}

int returnIfPositive(int input) {
	if (input > 0) {
		return input;
		} else if (input < 0) {
		return 0;
		} else if (input == 0) {
		return input;
	}
	return 1;
}

int evalSpeedLimit(int input) {
	if (input > 0 || input < speedLimit) {
		return input;
	} else if (input < 0 || input > mathNegative(speedLimit)) {
		return input;
	} else if (input == speedLimit || input == mathNegative(speedLimit)) {
		return speedLimit;
	}
	return 0;
}

int returnIfNegative(int input) {
	if (input > 0) {
		return 0;
		} else if (input < 0) {
		return input;
		} else if (input == 0) {
		return input;
	}
	return 0;
}

void joystickUpdateVar() {
	// Left knob
	j1[0] = returnIfPositive(vexRT[Ch3]); //U
	j1[1] = returnIfNegative(vexRT[Ch3]); //D
	j1[2] = returnIfNegative(vexRT[Ch4]); //L
	j1[3] = returnIfPositive(vexRT[Ch4]); //R
	// Right knob
	j2[0] = returnIfPositive(vexRT[Ch2]); //U
	j2[1] = returnIfNegative(vexRT[Ch2]); //D
	j2[2] = returnIfNegative(vexRT[Ch1]); //L
	j2[3] = returnIfPositive(vexRT[Ch1]); //R
	// Left button groups
	j3[0] = vexRT[Btn7U]; //U
	j3[1] = vexRT[Btn7D]; //D
	j3[2] = vexRT[Btn7L]; //L
	j3[3] = vexRT[Btn7R]; //R
	// Right button groups
	j4[0] = vexRT[Btn8U]; //U
	j4[1] = vexRT[Btn8D]; //D
	j4[2] = vexRT[Btn8L]; //L
	j4[3] = vexRT[Btn8R]; //R
	// Left trigger buttons
	j5[0] = vexRT[Btn5U]; //U
	j5[1] = vexRT[Btn5D]; //D
	// Right trigger buttons
	j6[0] = vexRT[Btn6U]; //U
	j6[1] = vexRT[Btn6D]; //D
}

void moveDriveMotor() {
	motor[dm_w] = evalSpeedLimit(vexRT[Ch3]);
	motor[dm_e] = evalSpeedLimit(vexRT[Ch3]);
	motor[dm_n] = evalSpeedLimit(vexRT[Ch4]);
	motor[dm_s] = evalSpeedLimit(0 - vexRT[Ch4]);
}

int moveCatapaultMotor() {
	if (j4[0] == 1 && j4[1] == 1) {
		motor[cpm_l] = 0;
		motor[cpm_r] = 0;
	} else if (j4[1] == 1) {
		motor[cpm_l] = -127;
		motor[cpm_r] = -127;
	} else if (j4[0] == 1) {
		motor[cpm_l] = 127;
		motor[cpm_r] = 127;
	} else if (j4[1] == 0 || j4[0] == 0) {
		motor[cpm_l] = 0;
		motor[cpm_r] = 0;
	}
	return 1;
}

int moveReleaseMotor() {
	if (j4[2] == 1 && j4[3] == 1) {
		motor[rm_l] = 0;
		motor[rm_r] = 0;
	} else if (j4[2] == 1 && j4[3] == 0) {
		motor[rm_l] = 127;
		motor[rm_r] = 0;
	} else if (j4[2] == 0 && j4[3] == 1) {
		motor[rm_l] = -127;
		motor[rm_r] = 0;
	} else {
		motor[rm_l] = 0;
		motor[rm_r] = 0;
	}
	return 1;
}

void display() {
	clearLCDLine(0);
	clearLCDLine(1);
}

void tick() {
	clearTimer(T1);
	while(time1[T1] <= 1000 / tickRate) {
		display();
		joystickUpdateVar();
		moveDriveMotor();
		moveCatapaultMotor();
		moveReleaseMotor();
		sleep(30 - time1[T1]);
		tInc++;
	}
}

task main() {
	while(true) {
		tick();
	}
}
